# Generated by Django 4.2.6 on 2024-01-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_review_rating'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.ManyToManyField(to='doctor.availabletime'),
        ),
    ]
