# Generated by Django 4.2.6 on 2024-01-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
